config/routes.rb
Rails.application.routes.draw do

  resources :questions do
    collection do
      get :search
      get :autocomplete
    end
    resources :answers, only: [:create, :edit, :update, :destroy]
  end

  get :my_questions, to: 'users#my_questions', as: :my_questions
  get :my_answers, to: 'users#my_answers', as: :my_answers

  get 'login', to: redirect('/auth/google_oauth2'), as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')

  root to: 'pages#home'

  get '*path', to: 'application#not_found'
end

app/models/question.rb
class Question < ApplicationRecord

  WORD_START_FIELDS = ['title^10', 'body']
  searchkick word_start: WORD_START_FIELDS

  has_many :answers, dependent: :destroy
  has_many :answer_authors, through: :answers, source: :author
  belongs_to :author, class_name: "User", foreign_key: :user_id

  validates :title, presence: true, length: { maximum: 150 }
  validates :body, presence: true

  delegate :first_name, to: :author, prefix: true

  def search_data
    {
      title: title,
      body: body,
      user_id: user_id,
      created_at: created_at,
    }
  end

  def self.perform_search(params = {})
    search_term = params[:search].present? ? params[:search] : '*'

    search_params = default_search_params(params)
    search_params[:where][:user_id] = params[:author_id] if params[:author_id].present?
    self.search(search_term, search_params)
  end

  def self.autocomplete_search(params={})
    search_options = {
      fields: WORD_START_FIELDS,
      limit: 10,
      misspellings: { below: 5 },
    }
    Question.search(params[:query], search_options)
  end

  def has_author?(user)
    self.author == user
  end

  def fetch_answers(id=nil)
    options = {
      question_id: self.id,
      user_id: id
    }
    Answer.perform_search(options)
  end

  private
  def self.default_search_params(params = {})
    {
      fields: WORD_START_FIELDS,
      page: params[:page],
      per_page: PER_PAGE,
      where: {},
      order: { created_at: {order: "desc" } },
      includes: [:author, answers: :author]
    }
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show, :search, :autocomplete]
  before_action :set_question, only: [:show, :edit, :update, :destroy]
  before_action :verify_author, only: [:edit, :update]

  def index
    @questions = Question.perform_search(params)
  end

  def search
    @questions = Question.perform_search(params)
    render 'index'
  end

  def show
    @answers = @question.fetch_answers(current_user&.id)
    @new_answer = @question.answers.build if user_signed_in?
  end

  def new
    @question = Question.new
  end

  def edit
  end

  def create
    @question = Question.new(question_params)
    @question.author = current_user
    if @question.save
      redirect_to @question, notice: 'Question was successfully created.'
    else
      render :new
    end
  end

  def update
    if @question.update(question_params)
      redirect_to @question, notice: 'Question was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    if @question.destroy
      redirect_to questions_url, notice: 'Question was successfully destroyed.'
    else
      redirect_to questions_url, notice: 'Question is not destroyed.'
    end
  end

  def autocomplete
    @questions = Question.autocomplete_search(params)
    render json: @questions.collect(&:title)
  end

  private
  def set_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.fetch(:question).permit(:title, :body)
  end

  def verify_author
    unless @question.has_author?(current_user)
      redirect_to questions_path, notice: 'You are not allowed to perform this action'
    end
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper

  def can_submit_answer?(question)
    return false unless user_signed_in?
    return false if question.answer_authors.include?(current_user)
    return true
  end

  def show_saved_answers(answers)
    answers.select(&:persisted?) || []
  end
end

app/views/questions/_answers.html.erb
<ul class="list-group">
  <% answers.each do |answer| %>
    <%= render 'answers/answer', answer: answer %>
    <div class='margin-top-10'></div>
  <% end %>
</ul>

app/views/questions/_form.html.erb
<%= form_with(model: question, local: true) do |form| %>
  <% if question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
        <% question.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class='form-group'>
    <%= form.label :title %>
    <%= form.text_field :title, required: true, class: "form-control", maxlength: 150 %>
  </div>

  <div class='form-group'>
    <%= form.label :body %>
    <%= form.text_area :body, "data-provide" => "markdown", class: "mark form-control", rows: 20, required: true %>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/questions/_search_form.html.erb
<%= form_with(scope: :question, url: search_questions_path, local: true, method: :get, class: 'navbar-form navbar-left') do |f| %>
  <div class="form-group">
    <%= text_field_tag :search, params[:search], class: 'form-control typehead', placeholder: 'Search' %>
  </div>

  <%= submit_tag :search, class: 'btn btn-default' %>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
  <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
    <h1>Questions</h1>
  </div>
  <% if user_signed_in? %>
    <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
      <%= link_to 'New Question', new_question_path, class: 'btn btn-primary pull-right' %>
    </div>
  <% end %>
</div>
<hr>

<div class='clearfix'></div>

<ul class="list-group">
  <% @questions.each do |question| %>
    <li class='list-group-item col-md-12'>
      <%= link_to question do %>
        <div class='question-title col-md-8'>
          <%= question.title %>
        </div>
        <div class="pull-right col-md-4">
          <%= render_datetime(question.created_at) %>
        </div>
      <% end %>
    </li>
  <% end %>
</ul>

<%= paginate @questions %>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<%= link_to 'Back', questions_path, class: 'pull-right' %>

<div class="row">
  <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 col-center">
    <h2 class="main-heading">
      <%= @question.title %>
    </h2>

    <hr>

    <div class='markdown-container question-body'>
      <%= markdown(@question.body) %>
    </div>

    <small class='pull-right'><%= @question.author_first_name %></small>
    <div class="clearfix"></div>
    <small class='pull-right'><%= render_datetime(@question.created_at) %></small>
  </div>
</div>

<h2>Answers</h2>
<div class="question-answers">
  <%= render 'answers', answers: show_saved_answers(@answers) %>
</div>

<div class='new-answer'>
  <% if can_submit_answer?(@question) %>
    <%= render 'answers/form', question: @question, answer: @new_answer %>
  <% end %>
</div>