config/routes.rb
Rails.application.routes.draw do

  resources :questions do
    collection do
      get :search
      get :autocomplete
    end
    resources :answers, only: [:create, :edit, :update, :destroy]
  end

  get :my_questions, to: 'users#my_questions', as: :my_questions
  get :my_answers, to: 'users#my_answers', as: :my_answers

  get 'login', to: redirect('/auth/google_oauth2'), as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')

  root to: 'pages#home'

  get '*path', to: 'application#not_found'
end

app/views/shared/_flash.html.erb
<div class='clearfix'></div>
<% flash.each do |type, messages| %>
  <div class='alert alert-<%= alert_class(type) %> alert-dismissible fade in'>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <% if messages.present? and messages.is_a? Array %>
      <% messages.each do |message| %>
        <li><%= message.to_s %></li>
      <% end %>
    <% else %>
      <li><%= messages %></li>
    <% end %>
  </div>
<% end %>

app/views/shared/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">

    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Q-A APP", root_path, class: 'navbar-brand' %>
    </div>

    <%= render 'questions/search_form' %>

    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <li><%= link_to "My Questions", my_questions_path %></li>
        <li><%= link_to "My Answers", my_answers_path %></li>
        <li><%= link_to "Log out", logout_path %></li>
      <% else %>
        <li><%= link_to "Log In with Google", login_path %></li>
      <% end %>
    </ul>
  </div>
</nav>