config/routes.rb
Rails.application.routes.draw do

  resources :questions do
    collection do
      get :search
      get :autocomplete
    end
    resources :answers, only: [:create, :edit, :update, :destroy]
  end

  get :my_questions, to: 'users#my_questions', as: :my_questions
  get :my_answers, to: 'users#my_answers', as: :my_answers

  get 'login', to: redirect('/auth/google_oauth2'), as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')

  root to: 'pages#home'

  get '*path', to: 'application#not_found'
end

app/models/answer.rb
class Answer < ApplicationRecord

  WORD_START_FIELDS = ['body']
  searchkick word_start: WORD_START_FIELDS

  belongs_to :author, class_name: "User", foreign_key: :user_id
  belongs_to :question

  validates :body, presence: true
  validates :question_id, uniqueness: { scope: :user_id }

  delegate :first_name, to: :author, prefix: true

  def search_data
    {
      body: body,
      user_id: user_id,
      created_at: created_at,
      question_id: question_id,
    }
  end

  def self.perform_search(params = {})
    search_term = params[:search].present? ? params[:search] : '*'

    search_params = default_search_params(params)
    search_params[:where][:question_id] = params[:question_id] if params[:question_id].present?
    search_params[:boost_where][:user_id] =  { value: params[:user_id], factor:100 }  if params[:user_id].present?
    search_params[:where][:user_id] = params[:author_id] if params[:author_id].present?

    self.search(search_term, search_params)
  end

  def has_author?(user)
    self.author == user
  end

  private
  def self.default_search_params(params = {})
    {
      fields: WORD_START_FIELDS,
      page: params[:page],
      per_page: PER_PAGE,
      where: {},
      boost_where: {},
      order: {_score: :desc},
      includes:  :question
    }
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_question, only: [:create, :edit, :update, :destroy]
  before_action :set_answer, only: [:edit, :update, :destroy]
  before_action :verify_author, only: [:edit, :update]

  def create
    @answer = @question.answers.new(answer_params)
    @answer.author = current_user
    @answer.save
  end

  def edit
  end

  def update
    @answer.update(answer_params)
  end

  def destroy
    @answer.destroy
  end

  private
  def set_question
    @question = Question.find(params[:question_id])
  end

  def set_answer
    @answer = Answer.find(params[:id])
  end

  def answer_params
    params.fetch(:answer).permit(:body)
  end

  def verify_author
    unless @answer.has_author?(current_user)
      redirect_to questions_path, notice: 'You are not allowed to perform this action'
    end
  end

end

app/views/answers/_answer.html.erb
<li class="list-group-item col-md-12 answer-<%= answer.id %>">
  <%= markdown(answer.body) %>
  <% if answer.has_author?(current_user) %>
    <%= link_to 'Edit', edit_question_answer_path(@question, answer), remote: true, class: 'btn btn-warning' %>
    <%= link_to 'Delete', question_answer_path(@question, answer), method: :delete, remote: true, class: 'btn btn-danger' %>
  <% end %>
  <small class='pull-right'><%= answer.author_first_name %></small>
  <div class="clearfix"></div>
  <small class='pull-right'><%= render_datetime(answer.created_at) %></small>
</li>

app/views/answers/_form.html.erb
<%= form_with(model: [question, answer], local: false) do |form| %>
  <% if answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
        <% answer.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class='form-group'>
    <%= form.label :body, 'Your Answer' %>
    <%= form.text_area :body, "data-provide" => "markdown", class: "mark form-control", rows: 10, cols: 10, required: true %>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/answers/_new.html.erb
<%= form_with(model: [question, answer], local: true) do |form| %>
  <% if answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
        <% answer.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class='form-group'>
    <%= form.label :body, 'Your Answer' %>
    <%= form.text_area :body, "data-provide" => "markdown", class: "mark form-control", rows: 10, cols: 10 %>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/answers/create.js.erb
<% if @answer.errors.blank? %>
  $(".new-answer form").remove();
  $(".list-group").prepend("<%= j render(partial: 'answers/answer', locals: {answer: @answer}) %>");
<% end %>

app/views/answers/destroy.js.erb
<% unless @answer.persisted? %>
  $(".answer-<%= @answer.id %>").fadeOut();
  $(".new-answer").html("<%= j render(partial: 'answers/form', locals: {question: @question, answer: @question.answers.build}) %>");
  window.load_markdown_for_text_area();
<% end %>

app/views/answers/edit.js.erb
$(".answer-<%= @answer.id %>").html("<%= j render(partial: 'answers/form', locals: {question: @question, answer: @answer}) %>");
  window.load_markdown_for_text_area();

app/views/answers/update.js.erb
<% if @answer.errors.blank? %>
  $(".answer-<%= @answer.id %>").html("<%= j render(partial: 'answers/answer', locals: {answer: @answer}) %>");
<% end %>