config/routes.rb
Rails.application.routes.draw do

  resources :questions do
    collection do
      get :search
      get :autocomplete
    end
    resources :answers, only: [:create, :edit, :update, :destroy]
  end

  get :my_questions, to: 'users#my_questions', as: :my_questions
  get :my_answers, to: 'users#my_answers', as: :my_answers

  get 'login', to: redirect('/auth/google_oauth2'), as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')

  root to: 'pages#home'

  get '*path', to: 'application#not_found'
end

app/views/pages/dashboard.html.erb
<h1>Dashboard</h1>

app/views/pages/home.html.erb
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
  <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
    <h1>Recent Questions</h1>
  </div>
  <% if user_signed_in? %>
    <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
      <%= link_to 'New Question', new_question_path, class: 'btn btn-primary pull-right' %>
    </div>
  <% end %>
</div>
<hr>


<div class='clearfix'></div>

<ul class="list-group">
  <% @questions.each do |question| %>
    <li class='list-group-item col-md-12'>
      <%= link_to question do %>
        <div class='question-title col-md-8'>
          <%= question.title %>
        </div>
        <div class="pull-right col-md-4">
          <%= render_datetime(question.created_at) %>
        </div>
      <% end %>
    </li>
  <% end %>
</ul>

<%= link_to "More", questions_path, class: 'btn btn-success pull-right' %>

app/views/pages/login.html.erb
<%= link_to "Log In with Google", login_path %>